Update AdministratorCommands.pwn
LVPlayground/playground pull request #545
Opened 2020-05-08 06:47 UTC by Specifer

Implementing #544 /show discord

2020-05-08 15:34 UTC, RussellLVP requested changes

2020-05-08 15:34 UTC, RussellLVP commented on pawn/Elements/AdministratorCommands.pwn
> +    SendClientMessage(playerId, Color::Information, "Usage: /show [beg/caps/donate/forum/interior/nick/reg/report/rules/ship/spam/swear/discord/weaps]");
Please keep this list alphabetized.

2020-05-08 15:34 UTC, RussellLVP commented on pawn/Elements/AdministratorCommands.pwn
> +        format(g_message, sizeof(g_message), "Join us on Official LVP Discord Server at www.discord.sa-mp.nl ");
1. Official is not spelled with a capital,
  1. It's discord.sa-mp.nl, no use of "www." in front it it,
  1. No space at the end.

"Join us on the official LVP Discord server at discord.sa-mp.nl"

2020-05-08 16:13 UTC, Specifer commented on pawn/Elements/AdministratorCommands.pwn
> -        format(g_message, sizeof(g_message), "Join us on Official LVP Discord Server at www.discord.sa-mp.nl ");
@RussellLVP , Changes that had been requested has been made !

2020-05-08 16:13 UTC, Specifer commented on pawn/Elements/AdministratorCommands.pwn
> +    SendClientMessage(playerId, Color::Information, "Usage: /show [beg/caps/discord/donate/forum/interior/nick/reg/report/rules/ship/spam/swear/weaps]");
@RussellLVP , Changes that had been requested has been made !

2020-05-08 16:28 UTC, RussellLVP commented on pawn/Elements/AdministratorCommands.pwn
> +    else if (!strcmp(showParameter, "discord", true, 4)) {
The "4" in this command needs to be a "7", as it reflects the length of the string that has to be matched.

`/show discovery` will now also show this message, which isn't intentional.

2020-05-08 17:31 UTC, Specifer commented on pawn/Elements/AdministratorCommands.pwn
> +    else if (!strcmp(showParameter, "discord", true, 7)) {
@RussellLVP , updated here as well as in /guide request too . Feel free to use that as it has these script lines too

2020-05-13 21:58 UTC, merged

2020-05-13 21:58 UTC, RussellLVP commented
Thank you for your contribution, it will go live with LVP 44!