New patch 6
LVPlayground/playground pull request #709
Opened 2020-06-11 11:25 UTC by Specifer

Ping me if it shows any error, My local server is showing some streamer error currently.

2020-06-11 23:12 UTC, RussellLVP requested changes
Hi Specifer,

Thank you! I think this is fine if you could use the `//features/commands/commands.js` infrastructure for this, like you have before :) That makes it much easier too!

Thanks,
Russell

2020-06-12 03:06 UTC, Specifer commented
Ok, thank you for saying!

2020-06-12 05:13 UTC, Specifer commented
@RussellLVP, Done!

2020-06-12 11:09 UTC, RussellLVP commented
Why are you deleting `account_commands.js`? That certainly shouldn't be deleted! Looks good otherwise.

2020-06-12 11:53 UTC, Specifer commented on javascript/features/account/account_commands.js
> +    // on the server in general. Certain options are limited to VIPs like alias feature.
I had to do it since to bring it to github desktop, Hope you understand :D.

2020-06-12 13:27 UTC, Specifer commented
Did some changes in Onplayercommand.pwn :D.

2020-06-13 18:14 UTC, Specifer commented
@RussellLVP, Fixed the error. Feel free to merge.

2020-06-14 02:29 UTC, RussellLVP commented on pawn/Resources/Callbacks/OnPlayer/OnPlayerCommandText.pwn
> +    if(strcmp(cmd, "/guide", true) == 0 || !Player(playerid)->isAdministrator() || !Player(playerid)->isManagement())
Please undo these changes, they're not necessary.

2020-06-14 02:29 UTC, RussellLVP commented
Thank you! This is good to go if you could remove the two lines from the Pawn code, they're not necessary.

2020-06-14 05:11 UTC, Specifer commented
@RussellLVP, Done!

2020-06-19 11:47 UTC, RussellLVP approved these changes

2020-06-19 11:47 UTC, merged